on:
    push:
        branches:
            - main
        paths:
            - 'catalyst/**'
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: npm install
            - name: Build packages
              run: npm run build
            - name: Publish
              env:
                  NPM_TOKEN: ${{ secrets.CATALYST_NPM_TOKEN }}
              run: |
                  npm publish
