name: Publish @evolv-delivery/catalyst

on:
    push:
        branches:
            - main
        paths:
            - 'catalyst/**'

jobs:
    publish-npm:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  registry-url: https://registry.npmjs.org/
            - run: |
                  npm install
                  npm run build
                  npm publish
              env:
                  NPM_TOKEN: ${{ secrets.CATALYST_NPM_TOKEN }}
              working-directory: ./catalyst
