name: Publish Catalyst package

on:
    push:
        branches:
            - main
        paths:
            - 'catalyst/**'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - working-directory: ./catalyst
            - run: npm install
            - run: npm run build

    publish-npm:
        name: Publish
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  registry-url: https://registry.npmjs.org/
            - run: npm publish
              env:
                  NPM_TOKEN: ${{ secrets.CATALYST_NPM_TOKEN }}
              working-directory: ./catalyst
